version: '3'

services:
  nginx:
    volumes:
      - ./default.conf.production:/etc/nginx/conf.d/default.conf:ro  # Use production Nginx config
      - ../certs:/etc/nginx/certs:ro # Use Let's Encrypt certificates
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "443:443/udp" # HTTP/3 