version: '3'

services:
  nginx:
    volumes:
      - ./nginx.conf.local:/etc/nginx/conf.d/default.conf:ro  # Use local Nginx config
    ports:
      - "80:80"     # HTTP
      # You can enable these if using self-signed certs for local HTTPS
      # - "443:443"   # HTTPS
      # - "443:443/udp" # HTTP/3 